import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {NativeTestGLTFLoader} from './helpers/native-gltf.mjs';
import {inspectProportionsV5,partSemanticV5} from '../tools/audit-geometric-proportions-v5.mjs';
async function model(id,category='defenders'){const b=readFileSync(new URL('../public/assets/geometric/'+category+'/'+id+'.glb',import.meta.url));return(await new NativeTestGLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')).scene;}
test('real reduced Archer whole head passes; restoring oversized vertices is rejected despite unchanged metadata',async()=>{const root=await model('archer-1');assert.deepEqual(inspectProportionsV5(root,{id:'archer-1'}).failures,[]);const head=root.getObjectByName('head_pivot');head.scale.x*=1.12;assert.ok(inspectProportionsV5(root,{id:'archer-1'}).failures.some(r=>r.name.includes('contracted dimensions')));});
test('detached headgear is rejected even with intact head reduction metadata',async()=>{const root=await model('runebreaker-1');assert.deepEqual(inspectProportionsV5(root,{id:'runebreaker-1'}).failures,[]);let cap;root.traverse(n=>{if(n.isMesh&&partSemanticV5(n)==='Faceted work cap')cap=n;});assert.ok(cap);cap.position.x+=.20;assert.ok(inspectProportionsV5(root,{id:'runebreaker-1'}).failures.length);});
test('true folded closed cloak passes; a flattened plate with the same flags is rejected',async()=>{const root=await model('verdantguard','champions');assert.deepEqual(inspectProportionsV5(root,{id:'verdantguard'}).failures,[]);const capes=[];root.traverse(n=>{if(n.isMesh&&n.userData.semanticPart==='Real rear cape')capes.push(n);});assert.ok(capes.length);for(const cape of capes)cape.geometry.scale(1,1,0);assert.ok(inspectProportionsV5(root,{id:'verdantguard'}).failures.some(r=>r.name.includes('physical drape stations')||r.name.includes('closed cloth volume')));});
