import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {attackRig,previewGeometricAttack,updateGeometricPreview,attackMuzzle,disposeAttack,resetAttack,triggerAttack,animateAttack} from '../game/render/battle-animation.js';
import {geometricMetadata,animateGeometricEnemyMotion} from '../game/render/geometric-motion.js';
import {CombatEffects} from '../game/render/combat-effects.js';
const groups={
 'Defender weapons':['defenders/soldier-1','defenders/soldier-6','defenders/archer-6','defenders/runebreaker-6','defenders/cleric-6','defenders/mage-6','defenders/druid-6','defenders/frostwarden-6','defenders/stormcaller-6'],
 'Champion weapons':['champions/rimewatch','champions/kingsrangerguard','champions/wyvernhunter','champions/royalranger','champions/mechanicalgolem','champions/emeraldgolem','champions/winterhold','champions/kingdomprotector','champions/kingsreach','champions/stonewarden','champions/griffinbomber','champions/archbishop'],
 'Mounted / flying':['champions/embercrown','champions/worldfire','champions/thunderheart','champions/phoenix','champions/rangermentor','champions/roseguard','champions/frostblade','champions/archangel','champions/starfall','enemies/host_15','enemies/host_28','enemies/host_40'],
 'Clearance / spirit':['defenders/archer-1','defenders/archer-2','defenders/archer-3','defenders/soldier-2','defenders/soldier-3','defenders/soldier-4','defenders/soldier-5','champions/highking','champions/mothernature','champions/thornwarden','champions/elvenking'],
 'Enemy anatomy':['enemies/host_01','enemies/host_03','enemies/host_09','enemies/host_10','enemies/host_13','enemies/host_17','enemies/host_18','enemies/host_21','enemies/host_25','enemies/host_39','enemies/host_45','enemies/host_50']};
const select=document.querySelector('#group'),angle=document.querySelector('#angle'),effects=document.querySelector('#effects'),labels=document.querySelector('#labels'),status=document.querySelector('#status');
for(const name of Object.keys(groups)){const option=document.createElement('option');option.text=name;select.append(option);}
const roster=await(await fetch('/data/towers.json')).json(),enemyData=await(await fetch('/data/enemies.json')).json(),loader=new GLTFLoader(),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#ece9df');renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;document.body.append(renderer.domElement);renderer.setScissorTest(true);
let records=[],running=false,phase=0,elapsed=0,stamp=0,last=0;
function dispose(){for(const record of records){record.fx.dispose();disposeAttack(record.rig);record.scene.traverse(n=>{n.geometry?.dispose();for(const m of Array.isArray(n.material)?n.material:[n.material])m?.dispose();});}records=[];}
async function load(){running=false;document.querySelector('#play').textContent='Play';dispose();status.textContent='Loading actual GLBs';labels.replaceChildren();
 for(const path of groups[select.value]){const gltf=await loader.loadAsync('/assets/geometric/'+path+'.glb?t='+Date.now()),actor=gltf.scene;actor.animations=gltf.animations;const metadata=geometricMetadata(actor),id=path.split('/').at(-1),family=metadata.family||id.replace(/-\d$/,''),stats=roster[family]||{type:'physical'},scene=new THREE.Scene(),figure=new THREE.Group();figure.add(actor);figure.userData.body=actor;scene.add(figure);
 const bounds=new THREE.Box3().setFromObject(actor,true),size=bounds.getSize(new THREE.Vector3()),height=Math.max(size.y,.8),centre=bounds.getCenter(new THREE.Vector3()),camera=new THREE.PerspectiveCamera(35,1,.01,100),isEnemy=path.startsWith('enemies/'),rig=isEnemy?null:attackRig(actor,family,stats),source={family,id:0,tier:metadata.tier,x:0,z:0},target={id:1,x:0,z:-Math.max(2,height*1.25)},enemy={...enemyData[id],id:0,traveled:0,statuses:{}},fx=new CombatEffects(scene,{getMuzzle:(_source,out,options)=>attackMuzzle(rig,out,options),sourceHeight:height*.65,targetHeight:()=>height*.45});
 scene.add(new THREE.HemisphereLight('#fffdf1','#69778f',1.45));const light=new THREE.DirectionalLight('#fff7de',1.6);light.position.set(-3,7,-5);scene.add(light);const ground=new THREE.Mesh(new THREE.PlaneGeometry(height*8,height*8),new THREE.MeshStandardMaterial({color:'#e2e0d6',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.03;scene.add(ground);
 const label=document.createElement('div');label.className='label';label.textContent=id+' · '+(isEnemy?'production '+(enemy.flying?'flight':'gait'):metadata.attackStyle+' / '+rig.kind);labels.append(label);records.push({path,id,family,stats,source,target,actor,figure,enemy,scene,camera,rig,fx,height,centre,metadata,isEnemy});}
 phase=0;elapsed=0;pose(0);window.animationReview={records,groups};status.textContent=records.length+' native assets · paused at rest';}
function pose(p){phase=p;for(const r of records){r.fx.syncProjectiles([],elapsed);if(r.isEnemy)continue;resetAttack(r.rig);previewGeometricAttack(r.rig,{duration:1});updateGeometricPreview(r.rig,p);if(p===0)resetAttack(r.rig);if(p>=.42&&effects.checked){const shot={id:1,source:r.source,target:r.target,stats:r.stats,progress:Math.min(1,(p-.42)/.35),duration:.35,start:{x:0,z:0}};r.fx.event('shot',shot);r.fx.poseProjectile(r.fx.projectiles.get(1),elapsed);if(r.stats.burnAura&&r.metadata.attackStyle!=='breath'&&p<1){triggerAttack(r.rig,{breath:true,combatTime:p});r.rig.breathTrack.elapsed=p*r.rig.breathTrack.duration;animateAttack(r.rig,0);r.fx.event('aura-attack',{source:r.source,target:r.target,stats:r.stats});}}}status.textContent='phase '+p.toFixed(2)+' · '+(p<.42?'preparation':p<.6?'release/recovery':'return');}
function render(time){const dt=last?Math.min(.05,(time-last)/1000):0;last=time;if(running){elapsed+=dt*.65;const p=elapsed%1.6;if(p<=1)pose(p);else pose(0);for(const r of records)if(r.isEnemy){r.enemy.traveled=elapsed*r.enemy.speed;const bob=animateGeometricEnemyMotion(r.figure,r.enemy,elapsed);r.figure.position.y=(r.enemy.flying?.55:0)+bob;}}
 const width=innerWidth,height=innerHeight-62,rows=Math.ceil(Math.max(1,records.length)/4),tileW=width/4,tileH=height/rows;renderer.setSize(width,height,false);labels.style.gridAutoRows=tileH+'px';for(let i=0;i<records.length;i++){const r=records[i],col=i%4,row=Math.floor(i/4),x=col*tileW,y=height-(row+1)*tileH;r.camera.aspect=tileW/tileH;r.camera.updateProjectionMatrix();const h=r.height,offset=angle.value==='side'?[h*3.8,h*1.3,0]:angle.value==='front'?[0,h*1.3,-h*3.8]:angle.value==='back'?[-h*2.8,h*1.6,h*2.8]:[h*2.5,h*1.55,-h*3];r.camera.position.set(...offset);r.camera.lookAt(0,h*.48,0);renderer.setViewport(x,y,tileW,tileH);renderer.setScissor(x,y,tileW,tileH);renderer.render(r.scene,r.camera);}requestAnimationFrame(render);}
select.addEventListener('change',load);angle.addEventListener('change',()=>{});effects.addEventListener('change',()=>pose(phase));document.querySelector('#play').addEventListener('click',()=>{running=!running;document.querySelector('#play').textContent=running?'Pause':'Play';});for(const button of document.querySelectorAll('[data-phase]'))button.addEventListener('click',()=>{running=false;document.querySelector('#play').textContent='Play';pose(Number(button.dataset.phase));});
await load();requestAnimationFrame(render);
