import {readFileSync,writeFileSync} from 'node:fs';
import {EconomyManager} from '../game/core/progression.js';
const data=Object.fromEntries(['balance','waves','enemies'].map(k=>[k,JSON.parse(readFileSync(`data/${k}.json`,'utf8'))]));
const eco=new EconomyManager(data.balance),rows=[];let earned=eco.gold;
function buy(){while(eco.upgradeMastery());}
buy();rows.push({wave:0,earned,mastery:eco.mastery,gold:eco.gold});
for(const [i,wave] of data.waves.entries()){
  for(const group of wave.groups){const e=data.enemies[group.type];earned+=e.gold*group.count;eco.reward(e.gold*group.count,e.xp*group.count);}
  earned+=wave.reward;eco.reward(wave.reward,15);buy();rows.push({wave:i+1,earned,mastery:eco.mastery,gold:eco.gold});
}
const total=data.balance.mastery.reduce((n,m)=>n+m.cost,0),first=rows.find(r=>r.mastery===data.balance.mastery.length-1);
writeFileSync('artifacts/economy-report.json',JSON.stringify({total,firstMaxWave:first.wave,rows},null,2));
writeFileSync('docs/ECONOMY_BALANCE.md',`# Campaign economy and difficulty\n\nConstruction Mastery now has 15 upgrades, costing ${total.toLocaleString('en-US')} gold in total. With every enemy killed, all wave rewards collected, no theft, and all available gold devoted to mastery, it first reaches the maximum after wave ${first.wave}. Kingdom-level gates are included in this calculation. The fifth tier remains uncommon; tier VI still requires merging two tier V candidates in the same round. Current-round odds never change after buying mastery.\n\nDowngrade costs 200 gold, lowers a basic current candidate by exactly one tier, and immediately keeps it. The other four become walls. It cannot affect Tier I, retained defenders or champions. Demolition and champion improvements also delay mastery. Keep health cannot be purchased.\n\nEvery 50-wave campaign grants 250 placements, including kept defenders and walls. Demolished positions remain spent. The planner counts the union of the fixed plan and all existing occupied cells, and compares its missing cells against the remaining draws.\n\n## Perfect-income milestones\n\n| After wave | Total gold earned including initial 90 | Mastery | Unspent gold |\n|---:|---:|---:|---:|\n`+rows.filter(r=>[0,5,10,15,20,25,29,30,35,50].includes(r.wave)).map(r=>`| ${r.wave} | ${r.earned} | ${r.mastery}/15 | ${r.gold} |`).join('\n')+'\n\n## Enemy pressure\n\nCampaign HP multiplies the original curve by `1.15 + min(1.85, wave × 0.055)`. Armor grows with wave and role: plated brutes and shields require armor reduction or magic; light scouts and beasts retain lower armor; ritual casters have 12–24% magic resistance. Existing immunities, regeneration, evasion, reactive armor, mirror shields, disarm and flying routes remain active. Gold and XP rewards are unchanged. Beast-specific bonuses now apply to the mounted warbands.\n\nReproduce with `node tools/author-economy.mjs`, `node tools/author-campaign.mjs`, `node tools/economy-report.mjs` and `node tools/balance.mjs --campaign`. The campaign bot is a simple greedy player, not a proof of optimal play or final balance.\n');
console.log({total,firstMaxWave:first.wave});
